### ISSUE TITLE
Amandroid can not read APK files from the disk

### ISSUE THREAD

**Issue by vitaliiavdiienko** [sireum/amandroid#17]
Hi Developers,

i have faced with the following bug:

`java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
        at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.sireum.util.FileUtil$.listFiles(File.scala:51)
        at org.sireum.jawa.JawaCodeSource$.load(JawaCodeSource.scala:75)
        at org.sireum.amandroid.security.AmandroidSocket.loadApk(AmandroidSocket.scala:85)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:162)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:157)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:156)
        at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:137)
        at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)`

Exception doesn't depend on APKs. I am using the following mode:
`./sireum amandroid taintAnalysis -p -m 40 -to 60 -msg VERBOSE someapk.apk sourcessinks.txt`

BUT, it depends on the ENVIRONMENT:
- It doesn't work on Ubuntu 14.04
- BUT it does work on Ubuntu 12.04
- It does work on OSX 10.10
- It does work on Fedora 20
- BUT it doesn't work on Fedora 19

Best Regards,
Vitalii

**Comment by fgwei** [comment]
It works on all my environments including Ubuntu 14.04 and osx 10.10. I guess why sometimes it does not work is because of you didn't install lib32. You can give a try and let me know.

**Comment by vitaliiavdiienko** [comment]
Solved!

Thanks a lot!

P.S. But exception can be more informative :)

Best Regards,
Vitalii
