### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by yongabc** [sireum/amandroid#18]
Hi, I tested GenCallGraph with the sample apk "AndroidSpecific_PrivateDataLeak3.apk" from the source code (sireumdev, debug mode), I got following error messages.
However, it works from the executable Sireum Command Line Interface.

------------------------------------------------------------------------------------------------
An error occured on 20150125-211620
java.lang.ExceptionInInitializerError
	at org.sireum.pilar.parser.Parser$.parse(Parser.scala:91)
	at org.sireum.pilar.parser.Parser$.parse(Parser.scala:75)
	at org.sireum.pilar.parser.Parser$.parseWithErrorAsString(Parser.scala:61)
	at org.sireum.jawa.Transform$.parseCodes(Transform.scala:30)
	at org.sireum.jawa.Transform$.getSymbolResolveResult(Transform.scala:35)
	at org.sireum.jawa.JawaResolver$.forceResolveToHierarchy(JawaResolver.scala:131)
	at org.sireum.jawa.JawaResolver$.resolveToHierarchy(JawaResolver.scala:117)
	at org.sireum.jawa.JawaResolver$.tryResolveRecord(JawaResolver.scala:69)
	at org.sireum.jawa.Center$.tryLoadRecord(Center.scala:701)
	at org.sireum.amandroid.parser.LayoutFileParser.org$sireum$amandroid$parser$LayoutFileParser$$getLayoutClass(LayoutFileParser.scala:53)
	at org.sireum.amandroid.parser.LayoutFileParser$LayoutParser.child(LayoutFileParser.scala:103)
	at pxb.android.axml.AxmlReader.accept(AxmlReader.java:108)
	at org.sireum.amandroid.parser.LayoutFileParser$$anon$1.handleXMLFile(LayoutFileParser.scala:214)
	at org.sireum.amandroid.parser.AbstractAndroidXMLParser.handleAndroidXMLFiles(AbstractAndroidXMLParser.scala:52)
	at org.sireum.amandroid.parser.LayoutFileParser.parseLayoutFile(LayoutFileParser.scala:173)
	at org.sireum.amandroid.appInfo.AppInfoCollector$.analyzeLayouts(AppInfoCollector.scala:207)
	at org.sireum.amandroid.appInfo.AppInfoCollector.collectInfo(AppInfoCollector.scala:154)
	at org.sireum.amandroid.cli.GenCallGraph$$anonfun$genCallGraph$1.apply(GenCallGraph.scala:140)
	at org.sireum.amandroid.cli.GenCallGraph$$anonfun$genCallGraph$1.apply(GenCallGraph.scala:123)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at org.sireum.amandroid.cli.GenCallGraph$.genCallGraph(GenCallGraph.scala:122)
	at org.sireum.amandroid.cli.GenCallGraph$.main(GenCallGraph.scala:112)
	at org.sireum.amandroid.cli.GenCallGraph.main(GenCallGraph.scala)
Caused by: org.antlr.v4.runtime.RuntimeMetaData$VersionMismatchException: ANTLR Tool version 4.4 used for code generation does not match the current runtime version 4.3
	at org.antlr.v4.runtime.RuntimeMetaData.checkVersion(RuntimeMetaData.java:397)
	at org.sireum.pilar.parser.Antlr4PilarLexer.<clinit>(Antlr4PilarLexer.java:14)
	... 23 more

**Comment by yongabc** [comment]
I remove some projectes (sireum-cli, sireum-jawa,....) and add jars from the Sireum path/lib.
It seems to work.

**Comment by fgwei** [comment]
Sorry for the late reply. It seems little weird to me. Because I never get this problem before. Could give me little bit more info about your setup?
