### ISSUE TITLE
Error: Can not find or load main class  org.sireum.amandroid.cli.Decompiler

### ISSUE THREAD

**Issue by wyunchao** [sireum/amandroid#27]
Hi, when I run the command "sireum amandroid decompile /path/some.apk /outputPath", I get the error as the title says. I really dont know why.

**Comment by fgwei** [comment]
make sure you are using the dev version of sireum. Then do sireum uninstall all. Then run your command again. Hope this can fix it.

**Comment by wyunchao** [comment]
Thanks，as you say, I fix it, but another question comes. After running the command "sireum amandroid taintAnalysis -m 12 -p -o /outputPath /path/some.apk /your_Amandroid_Home/taintAnalysis/sourceAndSinks/TaintSourcesAndSinks.txt", I get the following output.

Total apks: 1

Error: null
Written: /home/yunchao/outputPath/.errorlog
Cleaning up unclosed ZipFile for archive /home/yunchao/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /home/yunchao/Sireum/apps/amandroid/Sources/droidBenchExtend/InterComponentCommunication_Explicit1.apk

**Comment by fgwei** [comment]
Could you show me the /home/yunchao/outputPath/.errorlog

**Comment by wyunchao** [comment]
An error occured on 20150416-085936
java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.sireum.util.FileUtil$.listFiles(File.scala:51)
	at org.sireum.jawa.JawaCodeSource$.load(JawaCodeSource.scala:75)
	at org.sireum.amandroid.security.AmandroidSocket.loadApk(AmandroidSocket.scala:84)
	at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:185)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:161)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:157)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:156)
	at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:137)
	at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)
