### ISSUE TITLE
"The following code has format problem"

### ISSUE THREAD

**Issue by vitaliiavdiienko** [sireum/amandroid#28]
Hi,

i am analysing an app and has the following error:

'An error occured on 20150410-133311
java.lang.RuntimeException: Following code has format problem:

        at org.sireum.jawa.JawaCodeSource$.org$sireum$jawa$JawaCodeSource$$getRecordName(JawaCodeSource.scala:85)
        at org.sireum.jawa.JawaCodeSource$$anonfun$load$1.apply(JawaCodeSource.scala:79)
        at org.sireum.jawa.JawaCodeSource$$anonfun$load$1.apply(JawaCodeSource.scala:77)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.sireum.jawa.JawaCodeSource$.load(JawaCodeSource.scala:76)
        at org.sireum.amandroid.security.AmandroidSocket.loadApk(AmandroidSocket.scala:84)
        at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:185)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:161)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:157)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:156)
        at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:137)
        at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)'

It is a development branch.

Thanks.

**Comment by fgwei** [comment]
Can you give me the app to test?
