### ISSUE TITLE
ZipException

### ISSUE THREAD

**Issue by alexrhein** [sireum/amandroid#30]
Hi,
I tried to run amandroid as stated on the website:
sireum amandroid taintAnalysis -m 12 -p -o /outputPath /path/some.apk /your_Amandroid_Home/taintAnalysis/sourceAndSinks/TaintSourcesAndSinks.txt

The analyzed apk was com.acj0.formsxpressdemo.apk from the playstore.
I used the Flowdroid format for Sources/Sinks, which I now know is incorrect.
However, I got a ZipException, which I imagine has nothing to do with the sources/sinks file:

java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at Main$$anon$1$SireumDistro$.unzip(sireum:1322)
	at Main$$anon$1$SireumDistro$.installApp(sireum:1003)
	at Main$$anon$1$SireumDistro$.downloadFile(sireum:962)
	at Main$$anon$1$SireumDistro$$anonfun$downloadNewFiles$1.apply(sireum:591)
	at Main$$anon$1$SireumDistro$$anonfun$downloadNewFiles$1.apply(sireum:586)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at Main$$anon$1$SireumDistro$.downloadNewFiles(sireum:586)
	at Main$$anon$1$SireumDistro$$anonfun$install$2.apply(sireum:568)
	at Main$$anon$1$SireumDistro$$anonfun$install$2.apply(sireum:557)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at Main$$anon$1$SireumDistro$.install(sireum:557)
	at Main$$anon$1$SireumDistro$.parseCliArgs(sireum:400)
	at Main$$anon$1$SireumDistro$.parseDistroArgs(sireum:340)
	at Main$$anon$1$SireumDistro$.delayedEndpoint$Main$$anon$1$SireumDistro$1(sireum:248)
	at Main$$anon$1$SireumDistro$delayedInit$body.apply(sireum:77)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$$anon$1$SireumDistro$.main(sireum:77)
	at Main$$anon$1.<init>(sireum:49)
	at Main$.main(sireum:49)
	at Main.main(sireum)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:175)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:157)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
	at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:205)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:67)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

**Comment by fgwei** [comment]
The problem is the university server (which is our current update site) is not stable. So the payload which required for your run does not download properly. You can try following commands:

1. sireum clean
2. sireum uninstall "Amandroid.sapp"
3. sireum install "Sireum Amandroid Cli"

Then if everything is fine, it should work.

**Comment by alexrhein** [comment]
Thanks, the download worked now.
