### ISSUE TITLE
Sireum/apps/amandroid/dex2pilar/linux64/newdex2pilar: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vitaliiavdiienko** [sireum/amandroid#36]
Hi,

i have downloaded the latest version of Strawberry Sireum stable distribution. But, it seems like some library is missed.

I am using Ubuntu 14.04 x64. How to solve those problems?

`An error occured on 20150609-104157
java.lang.RuntimeException: Error on running: /scratch/avdiienko/Sireum/apps/amandroid/dex2pilar/linux64/newdex2pilar
  Message: StringResult(/scratch/avdiienko/Sireum/apps/amandroid/dex2pilar/linux64/newdex2pilar: error while loading shared libraries: libc++.so: cannot open shared object file: No such file or directory
,127)
        at org.sireum.amandroid.decompile.Dex2PilarConverter$.convert(Dex2PilarConverter.scala:36)
        at org.sireum.amandroid.security.AmandroidSocket.loadApk(AmandroidSocket.scala:84)
        at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:183)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:159)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:155)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:154)
        at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:135)
        at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)
`

Thank you in advance.

Vitalii

**Comment by vitaliiavdiienko** [comment]
Solved with #2 from http://amandroid.sireum.org/docs/tutorial.html#troubleshooting

P.S. in my case libstdc++.so.6 was in /usr/lib/i386-linux-gnu

**Comment by fripSide** [comment]
Where is libc++.so？I can only find libstdc++.so.6 in CentOS.

**Comment by fgwei** [comment]
You can follow 2) from http://amandroid.sireum.org/docs/tutorial.html#troubleshooting
basically you need to do 
sudo ln -sf libstdc++.so.6 libc++.so
then add path to LD_LIBRARY_PATH
