### ISSUE TITLE
Error: android.util.TypedValue.coerceToString(II)Ljava/lang/String

### ISSUE THREAD

**Issue by vitaliiavdiienko** [sireum/amandroid#37]
Hi,
again, I am trying to run the latest version of Amandroid on Ubuntu 14.04 x64, but now on DEV branch of Strawberry.

`An error occured on 20150609-105548
java.lang.NoSuchMethodError: android.util.TypedValue.coerceToString(II)Ljava/lang/String;
        at brut.androlib.res.data.value.ResIntValue.encodeAsResXml(ResIntValue.java:45)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:45)
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:41)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:97)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:65)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:134)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:199)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:139)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at org.sireum.amandroid.decompile.AmDecoder$.decode(AmDecoder.scala:49)
        at org.sireum.amandroid.security.AmandroidSocket.loadApk(AmandroidSocket.scala:80)
        at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:183)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:159)
        at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:155)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:155)
        at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:135)
        at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)
`
Can you help me with this?

Thanks,

Vitalii

**Comment by fgwei** [comment]
It seems the problem comes from apktool. Is the same error happen on other apps?
--
Fengguo

**Comment by vitaliiavdiienko** [comment]
Yes, on all apps.

**Comment by ramkumark1** [comment]
Hi, I get the same error above. Need some inputs to resolve the problem, tried running with the latest version nightly build. The apks were developed with API22. Could that be a problem?

**Comment by fgwei** [comment]
It was a library conflict problem, not a problem with your api level. But it should be already resolved.
You can send me the .errorlog and also you can send me the app to test if possible.

**Comment by ramkumark1** [comment]
[Test.zip](https://github.com/sireum/amandroid/files/129998/Test.zip)


Hi, I have added the two apks I have used and error log. I was running taint analysis. Amandroid requires specific version of OpenJDK? I am using 1.7

**Comment by fgwei** [comment]
No, sireum folder contains all required library for Amandroid. Jdk is also included, which is JDK8.

**Comment by fgwei** [comment]
I tested the app on my machine. It seems no problem. Maybe your set up have some problem. Could you tell me your running OS, and how you setup sireum?

**Comment by ramkumark1** [comment]
I am running Ubuntu 14.4. Installed Sireum Strawberry, then Shortcake. Downloaded Docker containers. set the Scala options as given in this instruction http://sireum.org/software.html#strawberry

**Comment by ramkumark1** [comment]
Hi, if its the problem with installation i ll review again. I also found demo videos. If the problem still persists, i ll get back to you. Thanks for the support.

**Comment by fgwei** [comment]
I tested. This problem do exist in Ubuntu 14.04 with unknown reason... I made a fix and testing it again, I will let you know the result.

**Comment by fgwei** [comment]
Do a sireum update 
it should be ok now.

**Comment by ramkumark1** [comment]
Thanks for the support. Will update you if the issue persists.
