### ISSUE TITLE
Run sireum am android in my windows

### ISSUE THREAD

**Issue by Mac85** [sireum/amandroid#47]
HI friends, amandroid isn't works.Why?

![img_1176](https://cloud.githubusercontent.com/assets/15186904/12294064/db603ed8-b9f7-11e5-9761-893bdb203e85.JPG)

**Comment by fgwei** [comment]
Could you send me the .errorlog?

**Comment by Mac85** [comment]
Thank’s my fiend

**Comment by Mac85** [comment]
This is errorLog



An error occured on 20160113-183716
java.net.URISyntaxException: Illegal character in path at index 40: file:/C:/Users/emanuele/Desktop/analisi/\073ec89d7e88e362ba439f96e636c40fceee45a0f386c5630638fd1384dd26a2
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.sireum.amandroid.decompile.AmDecoder$.decode(AmDecoder.scala:38)
	at org.sireum.amandroid.decompile.ApkDecompiler$.decodeApk(ApkDecompiler.scala:19)
	at org.sireum.amandroid.decompile.ApkDecompiler$.decompile(ApkDecompiler.scala:54)
	at org.sireum.amandroid.alir.componentSummary.ApkYard.loadApk(ApkYard.scala:48)
	at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:179)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:144)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:135)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:135)
	at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:123)
	at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)

**Comment by fgwei** [comment]
I see. It's a bug introduced by me, I will fix it soon and let you know.

**Comment by Mac85** [comment]
ok thank's

**Comment by fgwei** [comment]
The bug is fixed. But the university server is currently down so the fix works for source code develop version, but cannot push to the command line version. The CLI version have to wait for the server to backup.

**Comment by fgwei** [comment]
The server is backed up. So it should be fine now.

**Comment by mohammadg** [comment]
@fgwei This bug just happened to me.

I downloaded vanilla Sireum (stable on Win64 from http://sireum.org/software.html#install).

Then I ran: 
```sireum install "Sireum Amandroid Cli"```

The output path is invalid as a /\ is always added.
Error log is the same as the one @Mac85 provided.

Am I doing something wrong or does the CLI version still need an update?

**Comment by fgwei** [comment]
@mohammadg That's little weird to me. Could you give me the full error message, then I can locate the line.

**Comment by mohammadg** [comment]
@fgwei It seems ```/\``` is added regardless of what output path I provide which makes it an invalid windows path.

```
An error occured on 20160529-210125
java.net.URISyntaxException: Illegal character in path at index 26: file:/F:/Amandroid/output/\00621E015191863041E78726B863B7E1374B17FDA690367878D1272B0E44B232
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.sireum.amandroid.decompile.AmDecoder$.decode(AmDecoder.scala:38)
	at org.sireum.amandroid.decompile.ApkDecompiler$.decodeApk(ApkDecompiler.scala:19)
	at org.sireum.amandroid.decompile.ApkDecompiler$.decompile(ApkDecompiler.scala:54)
	at org.sireum.amandroid.alir.componentSummary.ApkYard.loadApk(ApkYard.scala:48)
	at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:179)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:144)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:135)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:135)
	at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:123)
	at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)
```

**Comment by fgwei** [comment]
@mohammadg could you try on dev version? The stable version have been update for a long time.

**Comment by mohammadg** [comment]
@fgwei I will try dev version and report back. I only tested stable.

**Comment by mohammadg** [comment]
@fgwei Can confirm the dev version fixes this. The issue can be closed.
