### ISSUE TITLE
Error: String index out of range: -44

### ISSUE THREAD

**Issue by Mac85** [sireum/amandroid#48]
Hi, I analyzing of the application and several apps return this error:

Error: String index out of range: -44

What means it?

Thank's

**Comment by fgwei** [comment]
Have you do a sireum update? And you can also send me the .errorlog

**Comment by Mac85** [comment]
Yes it is update, this is l'error:

An error occured on 20160127-175738
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.sireum.jawa.alir.pta.suspark.PointerAssignmentGraph.getStaticCallee(PointerAssignmentGraph.scala:559)
	at org.sireum.jawa.alir.pta.suspark.PointerAssignmentGraph$$anonfun$processStaticCall$1.apply(PointerAssignmentGraph.scala:193)
	at org.sireum.jawa.alir.pta.suspark.PointerAssignmentGraph$$anonfun$processStaticCall$1.apply(PointerAssignmentGraph.scala:189)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.sireum.jawa.alir.pta.suspark.PointerAssignmentGraph.processStaticCall(PointerAssignmentGraph.scala:189)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.processStaticInfo(InterproceduralSuperSpark.scala:77)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.checkAndDoCall(InterproceduralSuperSpark.scala:256)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$$anonfun$workListPropagation$2.apply(InterproceduralSuperSpark.scala:129)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$$anonfun$workListPropagation$2.apply(InterproceduralSuperSpark.scala:121)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.workListPropagation(InterproceduralSuperSpark.scala:121)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.doPTA(InterproceduralSuperSpark.scala:72)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$$anonfun$pta$1.apply(InterproceduralSuperSpark.scala:58)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$$anonfun$pta$1.apply(InterproceduralSuperSpark.scala:57)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.pta(InterproceduralSuperSpark.scala:57)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.build(InterproceduralSuperSpark.scala:46)
	at org.sireum.jawa.alir.pta.suspark.InterproceduralSuperSpark$.apply(InterproceduralSuperSpark.scala:35)
	at org.sireum.jawa.alir.reachability.ReachabilityAnalysis$.getReachableMethods(ReachabilityAnalysis.scala:31)
	at org.sireum.amandroid.appInfo.ReachableInfoCollector$$anonfun$init$1.apply(ReachableInfoCollector.scala:67)
	at org.sireum.amandroid.appInfo.ReachableInfoCollector$$anonfun$init$1.apply(ReachableInfoCollector.scala:65)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.sireum.amandroid.appInfo.ReachableInfoCollector.init(ReachableInfoCollector.scala:65)
	at org.sireum.amandroid.appInfo.AppInfoCollector$.reachabilityAnalysis(AppInfoCollector.scala:301)
	at org.sireum.amandroid.appInfo.AppInfoCollector.collectInfo(AppInfoCollector.scala:182)
	at org.sireum.amandroid.alir.componentSummary.ApkYard.loadApk(ApkYard.scala:59)
	at org.sireum.amandroid.cli.TanitAnalysis$TaintTask.run(TaintAnalysis.scala:185)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:145)
	at org.sireum.amandroid.cli.TanitAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:136)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.sireum.amandroid.cli.TanitAnalysis$.taintAnalyze(TaintAnalysis.scala:136)
	at org.sireum.amandroid.cli.TanitAnalysis$.main(TaintAnalysis.scala:124)
	at org.sireum.amandroid.cli.TanitAnalysis.main(TaintAnalysis.scala)

**Comment by fgwei** [comment]
This errorlog sames like for a different problem, and I cannot locate this error trace, since it comes from an old version of amandroid. Are you using the dev version of sireum?

**Comment by Mac85** [comment]
Sireum v2 (Build dev-20151129-001951)

**Comment by fgwei** [comment]
Yeah, it is a pretty old version. 11/29/2015. Those problems fixed in latest version. You can do a sireum update.

**Comment by Mac85** [comment]
ok now upgrade :)
