### ISSUE TITLE
NoSuchMethodError after performing a clean reinstall of amandroid

### ISSUE THREAD

**Issue by kaushin** [sireum/amandroid#54]
Im pasting a full error trace ,  
java.lang.NoSuchMethodError: brut.androlib.res.data.ResResSpec.getType()Lbrut/androlib/res/data/ResTypeSpec;
	at org.sireum.amandroid.appInfo.AppInfoCollector$$anonfun$analyzeCallback$2$$anonfun$apply$1.apply$mcVI$sp(AppInfoCollector.scala:261)
	at org.sireum.amandroid.appInfo.AppInfoCollector$$anonfun$analyzeCallback$2$$anonfun$apply$1.apply(AppInfoCollector.scala:259)
	at org.sireum.amandroid.appInfo.AppInfoCollector$$anonfun$analyzeCallback$2$$anonfun$apply$1.apply(AppInfoCollector.scala:259)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at org.sireum.amandroid.appInfo.AppInfoCollector$$anonfun$analyzeCallback$2.apply(AppInfoCollector.scala:258)
	at org.sireum.amandroid.appInfo.AppInfoCollector$$anonfun$analyzeCallback$2.apply(AppInfoCollector.scala:256)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at org.sireum.amandroid.appInfo.AppInfoCollector$.analyzeCallback(AppInfoCollector.scala:256)
	at org.sireum.amandroid.security.apiMisuse.InterestingApiCollector.collectInfo(InterestingApiCollector.scala:51)
	at org.sireum.amandroid.run.security.HideAPI_run$HideAPIMisuseTask.run(HideAPI_run.scala:111)
	at org.sireum.amandroid.run.security.HideAPI_run$$anonfun$main$1.apply(HideAPI_run.scala:90)
	at org.sireum.amandroid.run.security.HideAPI_run$$anonfun$main$1.apply(HideAPI_run.scala:83)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at org.sireum.amandroid.run.security.HideAPI_run$.main(HideAPI_run.scala:82)
	at org.sireum.amandroid.run.security.HideAPI_run.main(HideAPI_run.scala)

**Comment by fgwei** [comment]
Do a sireum update. Then try again

**Comment by kaushin** [comment]
Thanks , that worked, Sry for the late reply, had family issues
