### ISSUE TITLE
Error from IntentInjection_run after i install new amandroid source

### ISSUE THREAD

**Issue by RohitSh26** [sireum/amandroid#55]
-Rohit BGSU
`org.sireum.amandroid.run.security.IntentInjection_run`

command line arguments:
`/Users/rohitsharma/Desktop/Sireum/apks/com.fcbh.dbp.BibleSocietyOfPhilippines_3.1.0.apk
/Users/rohitsharma/Desktop/Sireum/output`

Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.sireum.util.FileUtil$.listFiles(File.scala:45)
	at org.sireum.amandroid.run.security.IntentInjection_run$.main(IntentInjection_run.scala:145)
	at org.sireum.amandroid.run.security.IntentInjection_run.main(IntentInjection_run.scala)

**Comment by fgwei** [comment]
Yeah, its expect a folder instead of a apk.
